//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ded_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelEntities : DbContext
    {
        public HotelEntities()
            : base("name=HotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Comfort> Comforts { get; set; }
        public virtual DbSet<Date> Dates { get; set; }
        public virtual DbSet<Entry> Entries { get; set; }
        public virtual DbSet<Number> Numbers { get; set; }
        public virtual DbSet<Placing> Placings { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<State> States { get; set; }
    }
}
