//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ded_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Number
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Number()
        {
            this.Dates = new HashSet<Date>();
        }
    
        public int ID_Number { get; set; }
        public string place_type { get; set; }
        public string comfort_type { get; set; }
        public Nullable<int> isFree { get; set; }
        public byte[] imageNumber { get; set; }
    
        public virtual Comfort Comfort { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Date> Dates { get; set; }
        public virtual Placing Placing { get; set; }
    }
}
